# Generated by Django 5.1.4 on 2024-12-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pratos_ingredientes_alter_pratos_nome_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pratos',
            new_name='Prato',
        ),
    ]
